-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZEIuwtYk6LAXex+4
c/HFgi/o1foHxo55rH4AjLhW4QmgCgYIKoZIzj0DAQehRANCAAQYQmkDmBXTNVQr
fib2iU1RDPbVaQdcvhlSevl2+CBxBSWF4Vkbrpf2RuLX1zJHy4S9jhwUM+ooIb/6
y8IGyGKZ
-----END PRIVATE KEY-----